### ISSUE TITLE
How was the data generated?

### ISSUE THREAD

**Issue by takeru1205** [HCIILAB/SCUT-FBP5500-Database-Release#21]
Hi,
I'm trying to train the model with pytorch.
The training data looks exists in "data/faces" directory, and they are named "ftwXXX.jpg".
I downloaded SCUT-FBP5500-Database from Google Drive. But their name are "AFXXX.jpg".

I converted via "pts2txt.py", but i couldn't get them like "ftwXXX.jpg".

So how can I generate the training data?

**Comment by Marshal1l** [comment]
I also have this problem，How's it going for you?

**Comment by takeru1205** [comment]
Sorry,
I couldn't solve it, just gave up.
