### ISSUE TITLE
Tutorial on Training Neural Network on this dataset

### ISSUE THREAD

**Issue by ygrayson** [HCIILAB/SCUT-FBP5500-Database-Release#6]
Is there any tutorial on how to train AlexNet, ResNet-18, ResNeXt-50 or any other neural network on this dataset?

Any related paper to look into?

**Comment by HCIILAB** [comment]
The training tutorial has been uploaded

**Comment by ygrayson** [comment]
Thank you very much!

**Comment by quocnhat** [comment]
Could you help please, what is root file in forward.py? there is no ../data/faces folder.
